### ISSUE TITLE
Cannot build rfid-sl030

### ISSUE THREAD

**Issue by ghost** [mcqn/rfid-sl030#1]
Hi,

When I execute "npm install rfid-sl030", I get build error.

../src/ffi.cc: In static member function ‘static v8::Handle<v8::Value> FFI::FFICall(const int&)’:
../src/ffi.cc:290:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/ffi.cc: In static member function ‘static v8::Handle<v8::Value> FFI::FFICallAsync(const int&)’:
../src/ffi.cc:329:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
ffi_bindings.target.mk:99: recipe for target 'Release/obj.target/ffi_bindings/src/ffi.o' failed
make: *** [Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/home/pi/node_programs/PiPrintCopy/node_modules/exec-sync/node_modules/ffi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.38-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/node_programs/PiPrintCopy/node_modules/exec-sync/node_modules/ffi
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
PiPrintCopyAgent@1.0.0 /home/pi/node_programs/PiPrintCopy
├── UNMET PEER DEPENDENCY @angular/common@2.1.2
├── UNMET PEER DEPENDENCY @angular/core@2.1.2
├── UNMET PEER DEPENDENCY @angular/http@2.1.2
├── UNMET PEER DEPENDENCY rxjs@5.1.0
└── UNMET PEER DEPENDENCY zone.js@0.6.26

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN @angular/core@2.1.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/http@2.1.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/core@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/common@^2.2.0 but none was installed.
npm WARN @angular/material@2.0.0-beta.1 requires a peer of @angular/http@^2.2.0 but none was installed.
npm WARN @angular/router@3.1.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN angular-in-memory-web-api@0.1.17 requires a peer of rxjs@5.0.0-rc.4 but none was installed.
npm WARN angular-in-memory-web-api@0.1.17 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN PiPrintCopyAgent@1.0.0 No description
npm WARN PiPrintCopyAgent@1.0.0 No repository field.
npm ERR! Linux 4.4.38-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "rfid-sl030"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! ffi@1.2.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@1.2.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/node_programs/PiPrintCopy/npm-debug.log

**Comment by amcewen** [comment]
Hmm.  I'm not sure I can offer much help, I'm afraid - it looks like ffi isn't compiling, but that would be issues with ffi rather than rfid-sl030.  One thing I've spotted that's different from the system I'm deploying it on is that you look like you've got npm version 4.1.2 whereas I've been using v2.x (2.15.11 on a particular system I've got to hand).

Does switching to an earlier version of npm fix things?

**Comment by ghost** [comment]
I tried but I got the same error.
    I am use nodejs 7.5.0.
    
    
    On 02/13/2017 03:39 PM, Adrian McEwen
      wrote:
    
    
      Hmm. I'm not sure I can offer much help, I'm afraid - it looks
        like ffi isn't compiling, but that would be issues with ffi
        rather than rfid-sl030. One thing I've spotted that's different
        from the system I'm deploying it on is that you look like you've
        got npm version 4.1.2 whereas I've been using v2.x (2.15.11 on a
        particular system I've got to hand).
      Does switching to an earlier version of npm fix things?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mcqn/rfid-sl030","title":"mcqn/rfid-sl030","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mcqn/rfid-sl030"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amcewen in #1: Hmm.  I'm not sure I can offer much help, I'm afraid - it looks like ffi isn't compiling, but that would be issues with ffi rather than rfid-sl030.  One thing I've spotted that's different from the system I'm deploying it on is that you look like you've got npm version 4.1.2 whereas I've been using v2.x (2.15.11 on a particular system I've got to hand).\r\n\r\nDoes switching to an earlier version of npm fix things?"}],"action":{"name":"View Issue","url":"https://github.com/mcqn/rfid-sl030/issues/1#issuecomment-279410032"}}}

**Comment by amcewen** [comment]
Hmm.  Good point on the nodejs version - it went through some fairly big changes recently didn't it?  On the Pi I've been using I'm on version 10:

```
$ node --version
v0.10.29
```

**Comment by ghost** [comment]
I understand you are yout maintaining the project anymore, right?
    
    
    On 02/13/2017 04:30 PM, Adrian McEwen
      wrote:
    
    
      Hmm. Good point on the nodejs version - it went through some
        fairly big changes recently didn't it? On the Pi I've been using
        I'm on version 10:
      $ node --version
v0.10.29

      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mcqn/rfid-sl030","title":"mcqn/rfid-sl030","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mcqn/rfid-sl030"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amcewen in #1: Hmm.  Good point on the nodejs version - it went through some fairly big changes recently didn't it?  On the Pi I've been using I'm on version 10:\r\n\r\n```\r\n$ node --version\r\nv0.10.29\r\n```\r\n"}],"action":{"name":"View Issue","url":"https://github.com/mcqn/rfid-sl030/issues/1#issuecomment-279424793"}}}

**Comment by amcewen** [comment]
I've just published v0.1.1 which builds on the version of node in the latest Raspbian distro - node v4.8.2.
